# Generated by Django 4.2.24 on 2025-12-31 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_product_offer_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('section_type', models.CharField(choices=[('banner', 'Banner Products'), ('featured', 'Featured Products'), ('deals', 'Deals of the Day'), ('new_arrival', 'New Arrivals'), ('best_seller', 'Best Sellers')], max_length=20, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='HomepageProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.product')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homepage_products', to='adminapp.homepagesection')),
            ],
            options={
                'ordering': ['display_order'],
                'unique_together': {('section', 'product')},
            },
        ),
    ]
