# Generated by Django 4.2.24 on 2026-01-01 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_homepagesection_homepageproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagesection',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='homepage_sections', to='adminapp.category'),
        ),
        migrations.AddField(
            model_name='homepagesection',
            name='display_type',
            field=models.CharField(choices=[('manual', 'Manual Products'), ('category', 'By Category')], default='manual', max_length=20),
        ),
    ]
