# Generated by Django 4.2.24 on 2026-01-04 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0006_coupon_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='discount_value',
            new_name='discount',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='discount_type',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='max_discount',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='min_order_amount',
        ),
    ]
