# Generated by Django 4.2.24 on 2026-01-09 03:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0010_replacementorder_replacementorderitem_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cancel_reason',
        ),
        migrations.RemoveField(
            model_name='order',
            name='cancelled_at',
        ),
        migrations.RemoveField(
            model_name='order',
            name='razorpay_order_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='razorpay_payment_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='razorpay_signature',
        ),
        migrations.RemoveField(
            model_name='order',
            name='refund_account_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='refund_account_number',
        ),
        migrations.RemoveField(
            model_name='order',
            name='refund_bank_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='refund_ifsc',
        ),
        migrations.RemoveField(
            model_name='order',
            name='refund_status',
        ),
        migrations.RemoveField(
            model_name='replacementorder',
            name='expected_delivery',
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='replacement_order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_item', to='userapp.replacementorder'),
        ),
        migrations.AlterField(
            model_name='replacementorder',
            name='status',
            field=models.CharField(choices=[('PROCESSING', 'Processing'), ('SHIPPED', 'Shipped'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='PROCESSING', max_length=20),
        ),
    ]
