# Generated by Django 4.2.24 on 2026-05-20 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0012_order_cancel_reason_order_cancelled_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='razorpay_order_id',
            new_name='stripe_payment_intent',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='razorpay_payment_id',
            new_name='stripe_session_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='razorpay_signature',
        ),
    ]
