# Generated by Django 4.2.24 on 2026-05-23 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0013_rename_razorpay_order_id_order_stripe_payment_intent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='stripe_session_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
